# Generated by Django 4.2.6 on 2023-10-05 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "link",
                    models.CharField(max_length=128, verbose_name="Ссылка на урок"),
                ),
                (
                    "viewing",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Длительность просмотра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullName",
                    models.CharField(
                        default="Неизвестно", max_length=64, verbose_name="Ф.И.О."
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="Неизвестно", max_length=64, verbose_name="Email-адрес"
                    ),
                ),
                (
                    "timeView",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Время просмотра"
                    ),
                ),
                (
                    "checkView",
                    models.BooleanField(
                        verbose_name="Статус Просмотрено / Не просмотрено"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson",
                        to="myapp.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
                "ordering": ("pk",),
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="product",
            field=models.ManyToManyField(
                related_name="product", to="myapp.product", verbose_name="Продукт"
            ),
        ),
    ]
