# Generated by Django 4.2.6 on 2023-10-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="product",
        ),
        migrations.AddField(
            model_name="lesson",
            name="products",
            field=models.ManyToManyField(
                related_name="lessons", to="myapp.product", verbose_name="Продукт"
            ),
        ),
    ]
