# Generated by Django 4.2.6 on 2023-10-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_lesson_product_lesson_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="products",
        ),
        migrations.AddField(
            model_name="lesson",
            name="products",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="myapp.product",
                verbose_name="Продукт",
            ),
        ),
    ]
